"use client";
import Link from "next/link";
import { useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";

interface BookCoverProps {
  id: string;
  slug: string;
  title: string;
  coverImageId?: string;
  colorTag?: string;
  category?: string;
  size?: "large" | "small";
  className?: string;
}

function CoverImage({
  storageId,
  className,
}: {
  storageId: string;
  className?: string;
}) {
  const url = useQuery(api.writings.getFileUrl, { storageId });
  if (!url) return null;
  return <img src={url} alt="" className={className} />;
}

/**
 * BookCover component displays a writing as a professional book cover
 * with spine color, optional cover image, and theme-aware styling
 */
export default function BookCover({
  id,
  slug,
  title,
  coverImageId,
  colorTag,
  category,
  size = "large",
  className = "",
}: BookCoverProps) {
  const sizeClasses = {
    large: "book-cover-lg",
    small: "book-cover-sm",
  };

  // Extract first letter for monogram
  const monogramLetter = title ? title.trim().charAt(0).toUpperCase() : "P";

  return (
    <Link href={`/${slug}`} className={`book-cover-link ${className}`}>
      <div className={`book-cover ${sizeClasses[size]} ${!coverImageId ? "book-cover-classical" : ""}`}>
        {/* Book spine (left border with color tag) */}
        {colorTag && (
          <div
            className="book-cover-spine"
            style={{ backgroundColor: colorTag }}
            aria-hidden="true"
          />
        )}

        {/* Main content area */}
        {coverImageId ? (
          <div className="book-cover-content">
            <CoverImage
              storageId={coverImageId}
              className={`book-cover-image ${size === "large" ? "book-cover-image-lg" : "book-cover-image-sm"}`}
            />
            {/* Title and metadata */}
            <div className="book-cover-footer">
              <h3 className={`book-cover-title ${size === "large" ? "book-cover-title-lg" : "book-cover-title-sm"}`}>
                {title}
              </h3>

              {category && (
                <span className={`book-cover-category ${size === "large" ? "book-cover-category-lg" : "book-cover-category-sm"}`}>
                  {category}
                </span>
              )}
            </div>
          </div>
        ) : (
          /* Autogenerated classical hardcover layout when there is no cover image */
          <div 
            className="book-cover-classical-body"
            style={{ 
              backgroundColor: colorTag || "var(--color-primary)",
              color: "white" 
            }}
          >
            {/* Fine classical borders */}
            <div className="book-cover-classical-border-outer">
              <div className="book-cover-classical-border-inner">
                {/* Header category */}
                {category && (
                  <div className={`book-cover-classical-category ${size === "large" ? "text-xs" : "text-[8px]"}`}>
                    {category}
                  </div>
                )}

                {/* Centered monogram emblem */}
                <div className={`book-cover-classical-emblem ${size === "large" ? "emblem-lg" : "emblem-sm"}`}>
                  <span className="book-cover-classical-monogram">{monogramLetter}</span>
                </div>

                {/* Centered book title */}
                <h3 className={`book-cover-classical-title ${size === "large" ? "book-cover-classical-title-lg" : "book-cover-classical-title-sm"}`}>
                  {title}
                </h3>
                
                {/* Decorative sub-tag */}
                <div className="book-cover-classical-divider" />
                <span className="book-cover-classical-author">The Pen Book</span>
              </div>
            </div>
          </div>
        )}

        {/* Hover overlay for interactivity hint */}
        <div className="book-cover-overlay" aria-hidden="true" />
      </div>
    </Link>
  );
}

